- .github/workflows/build_docker.yml
- .gitmodules
This action only pushes the image on branch master.
> add docker-ci-script as github action.

- hsdp/config.go
- hsdp/data_source_iam_introspect.go
- hsdp/data_source_permissions.go
- hsdp/data_source_user.go
- hsdp/errors.go
- hsdp/provider.go
- hsdp/resource_iam_application.go
- hsdp/resource_iam_client.go
- hsdp/resource_iam_group.go
- hsdp/resource_iam_mfa_policy.go
- hsdp/resource_iam_organization.go
- hsdp/resource_iam_permission.go
- hsdp/resource_iam_proposition.go
- hsdp/resource_iam_role.go
- hsdp/resource_iam_service.go
- hsdp/resource_iam_user.go
The plugin is no longer IAM centric, whoop!
> IAM config is now 100% optional

- go.mod
- go.sum
- hsdp/config.go
- hsdp/data_source_credentials_access.go
- hsdp/provider.go
- hsdp/resource_container_host.go
- Supports using IAM service accounts
> service account support

- docs/data-sources/cdr_fhir_store.md
- docs/resources/cdr_org.md
- docs/resources/cdr_subscription.md
- go.mod
- go.sum
- hsdp/config.go
- hsdp/data_source_cdr_fhir_store.go
- hsdp/provider.go
- hsdp/resource_cdr_org.go
- hsdp/resource_cdr_subscription.go
- Add `part_of` support for `hsdp_cdr_org`
> Naming refactor 

- docs/resources/cdr_org.md
> Fix hsdp_cdr_org resource doc

- .gitignore
- CHANGELOG.md
- Dockerfile
- docs/resources/cdr_org.md
- docs/resources/container_host.md
- go.mod
- go.sum
- hsdp/resource_container_host.go
- hsdp/validators.go
> Container host subnet support

- docs/resources/iam_application.md
- docs/resources/iam_proposition.md
- go.mod
- go.sum
- hsdp/resource_dicom_object_store.go
- hsdp/resource_dicom_repository.go
- hsdp/resource_dicom_store_config.go
- hsdp/resource_iam_application.go
- hsdp/resource_iam_proposition.go
- hsdp/resource_metrics_autoscaler.go
When not set, random UUIDs will be generated for:
- Application
- Proposition
> Make global_reference_id's optional

- CHANGELOG.md
- docs/resources/iam_user.md
- go.mod
- go.sum
- hsdp/resource_iam_user.go
- Support user updates
- Support optional password for `hsdp_iam_user` for immediate account activation
> Implement IAM user updates and support immediate activation flow

- docs/resources/stl_config.md
- hsdp/resource_stl_config.go
- hsdp/tools_test.go
- main.go
- `ensure_tcp` and `ensure_udp` merge the ports listed with the current device settings
- implements #49
> Implement ensure_tcp and ensure_udp

- docs/data-sources/cdl_research_study.md
- docs/resources/cdl_research_study.md
- go.mod
- go.sum
- hsdp/data_source_cdl_research_study.go
- hsdp/resource_cdl_research_study.go
- hsdp/resource_iam_role.go
> Beginning support for $grant / $revoke

- docs/resources/connect_mdm_application.md
Updated Example for MDM Application.
> Updated MDM application doc for proposition_id

- docs/resources/connect_mdm_device_type.md
Updated the arguments in doc.
Though not clear on background of : 
* `commercial_type_number` - (Required) Commercial Type Number
> Connectmdm devicetype doc

- docs/resources/dicom_notification.md
- docs/resources/dicom_repository.md
- go.mod
- go.sum
- internal/provider/provider.go
- internal/services/dicom/resource_dicom_notification.go
> DICOM updates for December 2021 release

- docs/data-sources/connect_mdm_data_adapters.md
- docs/data-sources/connect_mdm_service_agent.md
- docs/data-sources/connect_mdm_service_agents.md
- go.mod
- go.sum
- internal/provider/provider.go
- internal/services/connect/mdm/data_source_connect_mdm_service_agent.go
- internal/services/connect/mdm/data_source_connect_mdm_service_agents.go
> Connect MDM: Add service agent data sources

- docs/resources/connect_mdm_oauth_client.md
- internal/services/connect/mdm/resource_connect_mdm_oauth_client.go
- internal/tools/tools.go
> Connect MDM: optionally bypass MDM scope limitations

- docs/resources/iam_org.md
- internal/services/iam/resource_iam_organization.go
> feat: support for synchronous IAM Organization deletes

- docs/data-sources/iam_permission.md
- docs/data-sources/iam_permissions.md
- internal/provider/provider.go
- internal/services/iam/data_source_iam_permission.go
- internal/services/iam/data_source_iam_permission_test.go
- internal/services/iam/data_source_iam_permissions.go
- internal/services/iam/data_source_iam_permissions_test.go
Also improve the hsdp_iam_permissions data source to expose
all available information
> IAM: Add hsdp_iam_permission data source

- docs/data-sources/docker_repository.md
- docs/resources/docker_repository.md
- go.mod
- go.sum
- internal/services/docker/repository/data_source_docker_registry.go
- internal/services/docker/repository/resource_docker_repository.go
> Docker: add latest_tag attribute (#201)

- docs/data-sources/iam_introspect.md
- internal/services/connect/mdm/resource_connect_mdm_proposition_test.go
- internal/services/iam/data_source_iam_introspect.go
> MDM: add acceptance test for MDM Proposition resource

- .gitignore
- docs/data-sources/iam_role_sharing_policies.md
- docs/resources/iam_role_sharing_policy.md
- go.mod
- go.sum
- internal/provider/provider.go
- internal/services/cdr/org/r4.go
- internal/services/cdr/org/stu3.go
- internal/services/cdr/practitioner/stu3.go
- internal/services/iam/data_source_iam_role_sharing_policies.go
- internal/services/iam/data_source_iam_role_sharing_policies_test.go
- internal/services/iam/role_sharing_policy/resource_role_sharing_policy.go
- internal/services/iam/role_sharing_policy/resource_role_sharing_policy_test.go
- internal/services/notification/resource_notification_subscriber.go
- internal/tools/tools.go
> IAM: Add IAM Role Sharing Policy resource. Refs #220

- docs/resources/dicom_notification.md
- go.mod
- go.sum
- internal/services/dicom/resource_dicom_notification.go
> DICOM Notification: deprecate/remove organization_id field

- go.mod
- go.sum
- internal/tools/tools.go
> Core: retry on HTTP 502 BAD Gateway by default

- go.mod
- go.sum
- internal/provider/provider.go
- internal/services/cdr/org/resource_cdr_org_test.go
> Core: Update Google FHIR #255

- docs/data-sources/s3creds_access.md
- docs/data-sources/s3creds_policy.md
- docs/resources/connect_mdm_authentication_method.md
- docs/resources/iam_client.md
- examples/logviewer/groups.tf
- examples/logviewer/provider.tf
- examples/logviewer/roles.tf
- examples/tdr/contracts.tf
- internal/services/iam/client/resource_iam_client_test.go
- internal/services/iam/device/resource_iam_device_test.go
- internal/services/iam/group/resource_iam_group_test.go
- internal/tools/random/NOTICE
- internal/tools/random/string.go
- internal/tools/tools.go
> Chore: use generated password everywhere #258

- docs/resources/iam_group.md
- internal/services/iam/group/resource_iam_group.go
- internal/services/iam/group/resource_iam_group_test.go
- internal/services/iam/group/resource_iam_group_v2.go
> IAM: conditionally check IAM Device/User mixups #265

- CHANGELOG.md
- go.mod
- go.sum
- internal/config/config.go
- internal/services/pki/resource_pki_cert.go
- internal/services/pki/resource_pki_tenant.go
> PKI: make UAA credentials fully optional #267

- docs/index.md
- go.sum
- internal/config/config.go
- internal/provider/provider.go
- internal/services/cdr/subscription/resource_cdr_subscription_test.go
> Core: support credentials config via JSON #270

- docs/resources/connect_mdm_proposition.md
- internal/services/connect/mdm/resource_connect_mdm_proposition.go
> MDM: expose `proposition_guid` #272

- internal/services/dicom/repository/resource_dicom_repository.go
> Chore: fix repository_organization_id usage #276

- .github/workflows/tests.yml
- docs/resources/iam_org.md
- internal/provider/provider.go
- internal/services/iam/organization/data_source_iam_organization.go
- internal/services/iam/organization/resource_iam_organization.go
- internal/services/iam/organization/resource_iam_organization_test.go
> Chore: refactor IAM Org layout and fix docs

- internal/services/iam/application/data_source_iam_application.go
- internal/services/iam/application/resource_iam_application.go
- internal/services/iam/application/resource_iam_application_test.go
- internal/services/iam/client/data_source_iam_client.go
- internal/services/iam/email_template/data_source_iam_email_templates.go
- internal/services/iam/email_template/resource_iam_email_template.go
- internal/services/iam/email_template/resource_iam_email_template_test.go
- internal/services/iam/group/data_source_iam_group.go
- internal/services/iam/group/data_source_iam_group_test.go
- internal/services/iam/proposition/data_source_iam_proposition.go
- internal/services/iam/proposition/resource_iam_proposition.go
- internal/services/iam/proposition/resource_iam_proposition_test.go
- internal/services/iam/role/data_source_iam_role.go
- internal/services/iam/role/resource_iam_role.go
- internal/services/iam/role/resource_iam_role_test.go
- internal/services/iam/role_sharing_policy/data_source_iam_role_sharing_policies.go
- internal/services/iam/role_sharing_policy/data_source_iam_role_sharing_policies_test.go
- internal/services/iam/service/data_source_iam_service.go
> IAM: add description to crossplane enabled resources #280

- docs/data-sources/config.md
- go.mod
- go.sum
> Core: add the pl (PrivateLink) region

- go.mod
- go.sum
> IAM: omit empty fields #288

- docs/resources/iam_application.md
- go.mod
- go.sum
- internal/services/iam/application/resource_iam_application.go
- internal/services/iam/application/resource_iam_application_test.go
- internal/services/iam/application/resource_iam_application_v0.go
> IAM: Implement proper IAM Delete support #291

- internal/services/dicom/repository/resource_dicom_repository.go
> Add workaround for DICOM 1.8/1.9 discrepancies

- docs/data-sources/iam_group.md
- go.mod
- go.sum
- internal/services/iam/group/data_source_iam_group.go
- internal/services/iam/group/data_source_iam_group_test.go
> IAM Group: add users, services and devices list to data source

- go.sum
- internal/services/iam/group/data_source_iam_group.go
- internal/services/iam/group/resource_iam_group.go
- internal/services/iam/group/resource_iam_group_test.go
> IAM Group: remove workarounds and use SCIM Group API v1

- .github/workflows/tests.yml
- docs/resources/pki_tenant.md
- internal/provider/provider.go
- internal/services/iam/application/resource_iam_application_test.go
- internal/services/pki/resource_pki_cert.go
- internal/services/pki/tenant/resource_pki_tenant.go
- internal/services/pki/tenant/resource_pki_tenant_v0.go
- Tenant CA TTL field
- Triggers field for Tenant
> PKI: tenant triggers and ttl

- internal/services/iam/group/resource_iam_group.go
> IAM Group: fix remove role usage #309

- docs/resources/iam_group.md
- internal/services/iam/group/resource_iam_group.go
- internal/services/iam/group/resource_iam_group_v3.go
- Useful for use in Crossplane
> Roles are now optional in Groups

- docs/resources/iam_user.md
- internal/services/iam/user/importer.go
- internal/services/iam/user/resource_iam_user.go
- This could be useful for Crossplane
> Support IAM User import using loginID
